// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using autobid.Domain.Database.EF;

#nullable disable

namespace autobid.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104092129_ConfigureCascadeDelete")]
    partial class ConfigureCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("autobid.Domain.Auctions.Auction", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("autobid.Domain.Auctions.Bid", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("autobid.Domain.Users.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("autobid.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistanceTraveledKm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EngineLiters")
                        .HasColumnType("REAL");

                    b.Property<int>("Fuel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTowHitch")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KmPerLiter")
                        .HasColumnType("REAL");

                    b.Property<int>("LicenseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("autobid.Domain.Users.CorporateCustomer", b =>
                {
                    b.HasBaseType("autobid.Domain.Users.User");

                    b.Property<string>("CVR")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal>("Credit")
                        .HasColumnType("TEXT");

                    b.HasIndex("CVR")
                        .IsUnique();

                    b.ToTable("CorporateUsers");
                });

            modelBuilder.Entity("autobid.Domain.Users.PrivateCustomer", b =>
                {
                    b.HasBaseType("autobid.Domain.Users.User");

                    b.Property<string>("CPR")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasIndex("CPR")
                        .IsUnique();

                    b.ToTable("PrivateCustomers");
                });

            modelBuilder.Entity("autobid.Domain.Auctions.Auction", b =>
                {
                    b.HasOne("autobid.Domain.Users.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("autobid.Domain.Vehicles.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("autobid.Domain.Auctions.Bid", b =>
                {
                    b.HasOne("autobid.Domain.Auctions.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId");

                    b.HasOne("autobid.Domain.Users.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("autobid.Domain.Users.CorporateCustomer", b =>
                {
                    b.HasOne("autobid.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("autobid.Domain.Users.CorporateCustomer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("autobid.Domain.Users.PrivateCustomer", b =>
                {
                    b.HasOne("autobid.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("autobid.Domain.Users.PrivateCustomer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("autobid.Domain.Auctions.Auction", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
